# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b85e2825d4f6c99dcd3339b48c96f163f196d3eecf986517242a969f37fd154f029e43769c21aa4479d271fb57c38f27d0567d2f47e322aa2920b1e90d4fdeb

test:
  secret_key_base: fef0d7835a4872be01d47ba6a4af4c0b55d171f72eac6f3d64c65d87862215c0f260006d09d7d9aa57f74b3438d8accbe831983564562cbc2a4347ad617fc9bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
